### ISSUE TITLE
macOS build support?

### ISSUE THREAD

**Issue by yamamushi** [hugoam/toy#3]
The website has an Apple logo on it, though I see it missing from the build instructions and of course there's no genie binary for it in the repo either. 

Is there a long-term plan to support macOS? Can it already be built perhaps?

**Comment by hugoam** [comment]
There is, but I haven't built the `genie` executable because I don't have a mac dev machine:
- go in `mud/3rdparty/GENie`
- go to `build/gmake.darwin`
- build (probably just calling `make` is ok)
- get the resulting executable from `GENie/bin/darwin` or somewhere like that and copy it to `toy/bin/darwin` then use that executable everytime you need to invoke `genie`

**Comment by hugoam** [comment]
As of https://github.com/hugoam/toy/commit/fc5f95ad9a7e8eae3d0951bb156b166c9d45236e toy builds on macOS and also has continuous integration set to build for OSX too : https://travis-ci.org/hugoam/toy
